// <auto-generated />
using DesafioFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioFull.Migrations
{
    [DbContext(typeof(DesafioFullContext))]
    [Migration("20210822144835_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DesafioFull.Models.Titulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<string>("DataVencimento");

                    b.Property<decimal>("Juros");

                    b.Property<decimal>("Multa");

                    b.Property<int>("NParcela");

                    b.Property<string>("Nome");

                    b.Property<int>("NumeroTitulo");

                    b.Property<decimal>("ValorParc");

                    b.HasKey("Id");

                    b.ToTable("Titulos");
                });
#pragma warning restore 612, 618
        }
    }
}
