// <auto-generated />
using System;
using DesafioFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioFull.Migrations
{
    [DbContext(typeof(DesafioFullContext))]
    partial class DesafioFullContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DesafioFull.Models.Parcelas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NumeroParcela");

                    b.Property<int>("PcNumTitulo");

                    b.Property<decimal>("ValorParcela");

                    b.Property<decimal>("ValorTotal");

                    b.Property<DateTime>("VencimentoParcela");

                    b.HasKey("id");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("DesafioFull.Models.Titulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<string>("DataVencimento");

                    b.Property<decimal>("Juros");

                    b.Property<decimal>("Multa");

                    b.Property<int>("NParcela");

                    b.Property<string>("Nome");

                    b.Property<int>("NumeroTitulo");

                    b.Property<int?>("Parcelasid");

                    b.Property<decimal>("ValorParc");

                    b.HasKey("Id");

                    b.HasIndex("Parcelasid");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("DesafioFull.Models.Titulos", b =>
                {
                    b.HasOne("DesafioFull.Models.Parcelas", "Parcelas")
                        .WithMany("Dividas")
                        .HasForeignKey("Parcelasid");
                });
#pragma warning restore 612, 618
        }
    }
}
